# Generated by Django 5.0.6 on 2025-09-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('container_no', models.CharField(max_length=100)),
                ('container_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_mark', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item_no_spec', models.CharField(max_length=100)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='order_pics/')),
                ('ctns', models.IntegerField()),
                ('qty_per_ctn', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('cbm_per_ctn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cbm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cbm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wt_per_ctn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_wt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=100)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.container')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.customer')),
            ],
        ),
    ]
