# Generated by Django 5.0.6 on 2025-09-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0002_alter_admintable_password_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
