# Generated by Django 5.0.6 on 2025-09-28 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0004_customer_is_first_login_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintable',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='admintable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
