# Generated by Django 5.0.6 on 2025-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0006_alter_order_cbm_alter_order_cbm_per_ctn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('shipping_mark', 'Shipping Mark'), ('description', 'Description'), ('item_no_spec', 'Item No/Spec'), ('material', 'Material'), ('ctns', 'CTNs'), ('qty_per_ctn', 'Qty/CTN'), ('total_qty', 'Total Qty'), ('unit', 'Unit'), ('cbm_per_ctn', 'CBM/CTN'), ('cbm', 'CBM'), ('total_cbm', 'Total CBM'), ('wt_per_ctn', 'Wt/CTN'), ('total_wt', 'Total Wt'), ('supplier', 'Supplier'), ('pictures', 'Picture')], max_length=50, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
