# Generated by Django 5.0.6 on 2025-10-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0008_orderfieldvisibilitynew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFieldVisibilityNew',
        ),
    ]
